name: Publish to GitHub Pages

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    name: "Publish"

    steps:
    - name: Install Dokkoo
      run: |
        curl -s https://raw.githubusercontent.com/Dirout/dokkoo/master/Cargo.toml --output Cargo.toml > /dev/null
        version=$( awk -F ' = ' '$1 ~ /version/ { gsub(/[\"]/, "", $2); printf("%s",$2) }' Cargo.toml )
        curl -s -L https://github.com/Dirout/dokkoo/releases/download/v${version}/dokkoo_${version}_amd64.deb --output dokkoo_${version}_amd64.deb > /dev/null
        sudo apt-get -qq install ./dokkoo_${version}_amd64.deb > /dev/null
        printf "Installed Dokkoo v${version}"
    - name: Checkout Mokk
      uses: actions/checkout@v2
      with:
          path: ./mokk
    - name: Checkout GitHub Pages environment
      uses: actions/checkout@v2
      with:
          ref: gh-pages
          path: ./gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: |
          find ./gh-pages -mindepth 1 ! -regex '^./gh-pages/.git\(/.*\)?' -delete
          cd ./mokk
          dokkoo build .     
    - name: Minimise
      run: |
          curl -s https://raw.githubusercontent.com/wilsonzlin/minify-html/master/Cargo.toml --output Cargo.toml > /dev/null
          version=$( awk -F ' = ' '$1 ~ /version/ { gsub(/[\"]/, "", $2); printf("%s",$2) }' Cargo.toml )
          curl -s -L https://wilsonl.in/minify-html/bin/${version}-linux-x86_64 --output minify-html > /dev/null
          chmod +x ./minify-html
          shopt -s globstar
          
          for h in ./mokk/output/**/*.html
          do
            hworkingdir=$(pwd)
            hminpath=${f/output/min}
            hwdout=${f/./$hworkingdir}
            hwdmin=${hminpath/./$hworkingdir}
            install -D /dev/null "$hwdmin"
            sudo ./minify-html -s "$hwdout" -o "$hwdmin" --css --js
          done
          
          for c in ./mokk/output/**/*.css
          do
            cworkingdir=$(pwd)
            cminpath=${f/output/min}
            cwdout=${f/./$cworkingdir}
            cwdmin=${cminpath/./$cworkingdir}
            install -D /dev/null "$cwdmin"
            sudo ./minify-html -s "$cwdout" -o "$cwdmin" --css
          done
          
          for j in ./mokk/output/**/*.js
          do
            workingdir=$(pwd)
            jminpath=${f/output/min}
            jwdout=${f/./$jworkingdir}
            jwdmin=${jminpath/./$jworkingdir}
            install -D /dev/null "$jwdmin"
            sudo ./minify-html -s "$jwdout" -o "$jwdmin" --js
          done
    - name: Prepare
      run: |
          cp -ar ./mokk/min/* ./gh-pages
          if [ -f "./mokk/postbuild.sh" ]; then
              chmod +x ./mokk/postbuild.sh && ./mokk/postbuild.sh
          fi
          touch ./gh-pages/.nojekyll
          tee -a ./gh-pages/.nojekyll > /dev/null <<EOT

          EOT
    - name: Publish
      run: |
          cd ./gh-pages
          git config --global user.name 'Dokkoo'
          git config --global user.email 'Dirout@users.noreply.github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -am "Publish Mokk to GitHub Pages"
          git push
